# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_bus', models.TextField()),
                ('id_ecran', models.TextField()),
                ('numero_matricule', models.IntegerField(default=0)),
                ('numero_ligne', models.IntegerField(default=0)),
                ('nombre_place', models.IntegerField(default=0)),
                ('status_ecran', models.CharField(choices=[('O', 'opened'), ('F', 'closed')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('surname', models.TextField()),
                ('tel', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='chauffeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_gestion.Driver'),
        ),
    ]
