# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristic',
            name='tel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='info',
            name='nombre_place',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='info',
            name='numero_ligne',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='info',
            name='numero_matricule',
            field=models.IntegerField(default=0),
        ),
    ]
