# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 18:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bus_gestion', '0002_auto_20170620_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='listed',
        ),
        migrations.AddField(
            model_name='bus',
            name='list_bus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bus_gestion.Info'),
            preserve_default=False,
        ),
    ]
