# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 00:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bus_gestion', '0003_auto_20170623_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='nom_bus',
            field=models.TextField(default=datetime.datetime(2017, 6, 24, 0, 23, 35, 300718, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
